name: Synchronize to forked repo
on:
  push:
    branches:
      - master

jobs:
  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.FORKED_REPO_TOKEN }}
          fetch-depth: 0
          ref: master

      - name: Add remote-url
        run: |
          git remote add forked-repo https://AAminha:${{ secrets.FORKED_REPO_TOKEN }}@github.com/AAminha/Neighbors-dev-Frontend
          git config user.name AAminha
          git config user.email dks4857@gmail.com

      - name: Push changes to forked-repo
        run: |
          git push -f forked-repo master

      - name: Clean up
        run: |
          git remote remove forked-repo
